# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_data.ipynb.

# %% auto 0
__all__ = ['POLYMER_FEATURES', 'get_polymer_data', 'get_photoswitch_data', 'get_mof_data']

# %% ../notebooks/00_data.ipynb 2
import os

import pandas as pd
from .helpers import HashableDataFrame
from collections import Counter
_THIS_DIR = os.path.abspath(os.path.dirname(os.path.abspath("")))


# %% ../notebooks/00_data.ipynb 5
POLYMER_FEATURES = [
    "num_[W]",
    "max_[W]",
    "num_[Tr]",
    "max_[Tr]",
    "num_[Ta]",
    "max_[Ta]",
    "num_[R]",
    "max_[R]",
    "[W]",
    "[Tr]",
    "[Ta]",
    "[R]",
    "rel_shannon",
    "length",
]


# %% ../notebooks/00_data.ipynb 6
def get_polymer_data(
    datadir="../data" # path to folder with data files
):
    return HashableDataFrame(pd.read_csv(os.path.join(datadir, "polymers.csv")))


# %% ../notebooks/00_data.ipynb 12
def get_photoswitch_data(
    datadir="../data" # path to folder with data files
):
    """By default we drop the rows without E isomer pi-pi* transition wavelength."""
    df =  pd.read_csv(os.path.join(datadir, "photoswitches.csv"))
    df.dropna(subset=['E isomer pi-pi* wavelength in nm'], inplace=True)
    df.drop_duplicates(subset=['SMILES'], inplace=True) # not sure how and if they did this in the initial work. There are certainly duplicates, e.g. C[N]1C=CC(=N1)N=NC2=CC=CC=C2 (see top)
    df.reset_index(inplace=True)
    return HashableDataFrame(df)

# %% ../notebooks/00_data.ipynb 25
def get_mof_data(
    datadir="../data" # path to folder with data files
):
    return HashableDataFrame(pd.read_csv(os.path.join(datadir, "mof.csv")))
