# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/06_helpers.ipynb.

# %% auto 0
__all__ = ['HashableDataFrame']

# %% ../notebooks/06_helpers.ipynb 1
from hashlib import sha256
from pandas.util import hash_pandas_object
from functools import lru_cache
import pandas as pd

# %% ../notebooks/06_helpers.ipynb 2
# taken from https://gist.github.com/dsevero/3f3db7acb45d6cd8e945e8a32eaca168
class HashableDataFrame(pd.DataFrame):
    def __init__(self, obj):
        super().__init__(obj)

    def __hash__(self):
        hash_value = sha256(hash_pandas_object(self, index=True).values)
        hash_value = hash(hash_value.hexdigest())
        return hash_value

    def __eq__(self, other):
        return self.equals(other)
